# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0


receivers:
  otlp:
    protocols:
      grpc:
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins: ["*"]
          allowed_headers: ["*"]

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
      #- "otel-collector:9464"  # metric
    resource_to_telemetry_conversion:
      enabled: true
    enable_open_metrics: true
    const_labels:
      label1: value1

  logging:
    verbosity: Detailed

processors:
  batch:

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

# connectors:
#   spanmetrics:

service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, zipkin, otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, prometheus]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
